---
abstract: '(alpha software) powerful utilities for common but difficult to nail HTML munging.'
author:
  - 'Ashley Pond V, C<< <ashley at cpan.org> >>.'
build_requires:
  File::Spec: 3
  Test::More: 0.5
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: XHTML-Util
no_index:
  directory:
    - inc
    - t
requires:
  CSS::Tiny: 0
  Encode: 2
  HTML::Entities: 0
  HTML::Selector::XPath: 0
  HTML::Tagset: 3.02
  HTML::TokeParser::Simple: 0
  Scalar::Util: 0
  XML::LibXML: 1.6
version: 0.02
